export const MOCK_MESSAGES = [
  { id: "m1", author: "assistant", content: "hogehoge？" },
  { id: "m2", author: "user", content: "No! fugafuga!" },
  { id: "m3", author: "assistant", content: "OK! fugafuga!" },
  { id: "m4", author: "user", content: "No! fuga↑fuga↓!" },
  { id: "m5", author: "assistant", content: "oh~~~~!hoge~~~~~↑↑↑!!!" },
  { id: "m6", author: "user", content: "Uh oh! fuga↑↑↑fuga↓↓↓!" },
  { id: "m7", author: "assistant", content: "oh~~~~!hoge~~~~~↑↑↑!!!" },
  { id: "m8", author: "user", content: "funky! funga↑↑↑funga↓↓↓!" },
  {
    id: "m9",
    author: "assistant",
    content: "oh~~~~!hoge~~~~~↑↑↑!!!",
  },
  { id: "m10", author: "user", content: "funky! funga↑↑↑funga↓↓↓!" },
  { id: "m11", author: "assistant", content: "oh~~~~!hoge~~~~~↑↑↑!!!" },
  { id: "m12", author: "user", content: "funky! funga↑↑↑funga↓↓↓!" },
  { id: "m13", author: "assistant", content: "oh~~~~!hoge~~~~~↑↑↑!!!" },
  { id: "m14", author: "user", content: "funky! funga↑↑↑funga↓↓↓!" },
  { id: "m15", author: "assistant", content: "oh~~~~!hoge~~~~~↑↑↑!!!" },
  { id: "m16", author: "user", content: "funky! funga↑↑↑funga↓↓↓!" },
  { id: "m17", author: "assistant", content: "oh~~~~!hoge~~~~~↑↑↑!!!" },
  { id: "m18", author: "user", content: "funky! funga↑↑↑funga↓↓↓!" },
  { id: "m19", author: "assistant", content: "oh~~~~!hoge~~~~~↑↑↑!!!" },
  { id: "m20", author: "user", content: "funky! funga↑↑↑funga↓↓↓!" },
  {
    id: "m21",
    author: "assistant",
    content: "おぉ〜〜〜〜〜〜!ほげ~~~~~↑↑↑!!!",
  },
  { id: "m22", author: "user", content: "ダァ！! ふんが↑↑↑ふんが↓↓↓!" },
];
